2016-04-23 21:35:29.478 [info] <0.7.0> Application lager started on node foo@ml905199
2016-04-23 21:35:29.522 [info] <0.7.0> Application sasl started on node foo@ml905199
2016-04-23 21:35:29.529 [info] <0.7.0> Application riak_sysmon started on node foo@ml905199
2016-04-23 21:35:29.564 [info] <0.7.0> Application os_mon started on node foo@ml905199
2016-04-23 21:35:29.567 [info] <0.274.0> alarm_handler: {set,{{disk_almost_full,"/"},[]}}
2016-04-23 21:35:29.574 [info] <0.7.0> Application basho_stats started on node foo@ml905199
2016-04-23 21:35:29.577 [info] <0.7.0> Application eleveldb started on node foo@ml905199
2016-04-23 21:35:29.580 [info] <0.7.0> Application erocksdb started on node foo@ml905199
2016-04-23 21:35:29.582 [info] <0.7.0> Application pbkdf2 started on node foo@ml905199
2016-04-23 21:35:29.584 [info] <0.7.0> Application poolboy started on node foo@ml905199
2016-04-23 21:35:29.602 [info] <0.305.0> Setup running ...
2016-04-23 21:35:29.604 [info] <0.305.0> Directories verified. Res = ok
2016-04-23 21:35:29.604 [info] <0.305.0> Setup finished processing hooks (Mode=normal)...
2016-04-23 21:35:29.604 [info] <0.7.0> Application setup started on node foo@ml905199
2016-04-23 21:35:29.638 [info] <0.312.0>@exometer_report:do_start_reporters:613 Starting reporters with []
2016-04-23 21:35:29.639 [info] <0.7.0> Application exometer_core started on node foo@ml905199
2016-04-23 21:35:29.682 [info] <0.7.0> Application clique started on node foo@ml905199
2016-04-23 21:35:29.754 [warning] <0.337.0>@riak_core_ring_manager:reload_ring:352 No ring file available.
2016-04-23 21:35:29.964 [info] <0.357.0>@riak_core_capability:process_capability_changes:555 New capability: {riak_core,vnode_routing} = proxy
2016-04-23 21:35:29.975 [info] <0.357.0>@riak_core_capability:process_capability_changes:555 New capability: {riak_core,staged_joins} = true
2016-04-23 21:35:29.984 [info] <0.357.0>@riak_core_capability:process_capability_changes:555 New capability: {riak_core,resizable_ring} = true
2016-04-23 21:35:29.994 [info] <0.357.0>@riak_core_capability:process_capability_changes:555 New capability: {riak_core,fold_req_version} = v2
2016-04-23 21:35:30.004 [info] <0.357.0>@riak_core_capability:process_capability_changes:555 New capability: {riak_core,security} = true
2016-04-23 21:35:30.013 [info] <0.357.0>@riak_core_capability:process_capability_changes:555 New capability: {riak_core,bucket_types} = true
2016-04-23 21:35:30.022 [info] <0.357.0>@riak_core_capability:process_capability_changes:555 New capability: {riak_core,net_ticktime} = true
2016-04-23 21:35:30.083 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-23 21:35:30.083 [info] <0.7.0> Application riak_core started on node foo@ml905199
2016-04-23 21:35:30.085 [info] <0.7.0> Application logger started on node foo@ml905199
2016-04-23 21:35:30.097 [error] <0.387.0> CRASH REPORT Process <0.387.0> with 0 neighbours exited with reason: call to undefined function local:init('Elixir.RicorEx.Sup', {local,'Elixir.RicorEx.Sup'}) in gen_server:init_it/6 line 352
2016-04-23 21:35:30.099 [error] <0.385.0> CRASH REPORT Process <0.385.0> with 0 neighbours exited with reason: {{undef,[{local,init,['Elixir.RicorEx.Sup',{local,'Elixir.RicorEx.Sup'}],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,287}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.RicorEx',start,[normal,[]]}} in application_master:init/4 line 134
2016-04-23 21:35:30.100 [info] <0.322.0>@riak_core_app:stop:114 Stopped  application riak_core.
2016-04-23 21:35:30.105 [info] <0.7.0> Application ricor_ex exited with reason: {{undef,[{local,init,['Elixir.RicorEx.Sup',{local,'Elixir.RicorEx.Sup'}],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,287}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.RicorEx',start,[normal,[]]}}
2016-04-23 21:35:30.105 [info] <0.7.0> Application logger exited with reason: stopped
2016-04-23 21:35:30.105 [info] <0.7.0> Application riak_core exited with reason: stopped
2016-04-23 21:35:30.105 [error] <0.6.0> gen_event 'Elixir.Logger.ErrorHandler' installed in error_logger terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"cannot use Logger, the :logger application is not running">>} in 'Elixir.Logger.Config':'__data__'/0 line 53
2016-04-23 21:35:30.105 [info] <0.7.0> Application clique exited with reason: stopped
2016-04-23 21:35:30.107 [info] <0.7.0> Application exometer_core exited with reason: stopped
2016-04-23 21:35:30.108 [info] <0.7.0> Application setup exited with reason: stopped
2016-04-23 21:35:30.108 [info] <0.7.0> Application poolboy exited with reason: stopped
2016-04-23 21:35:30.108 [info] <0.7.0> Application pbkdf2 exited with reason: stopped
2016-04-23 21:35:30.108 [info] <0.7.0> Application erocksdb exited with reason: stopped
2016-04-23 21:35:30.108 [info] <0.7.0> Application eleveldb exited with reason: stopped
2016-04-23 21:35:30.108 [info] <0.7.0> Application basho_stats exited with reason: stopped
2016-04-23 21:35:30.108 [info] <0.274.0> alarm_handler: {clear,{disk_almost_full,"/"}}
2016-04-23 21:35:30.109 [info] <0.7.0> Application os_mon exited with reason: stopped
2016-04-23 21:35:30.110 [info] <0.7.0> Application riak_sysmon exited with reason: stopped
2016-04-23 21:35:30.110 [info] <0.7.0> Application sasl exited with reason: stopped
